### ISSUE TITLE
能提供类似mediaplayer的setaudiostreamtype方法吗

### ISSUE THREAD

**Issue by xiezhanyan** [ViTess/Android-OMEPlayer#1]
你好,能增加这个接口吗,能实现吗?

**Comment by ViTess** [comment]
@xiezhanyan 不好意思，最近有(jiu)点(shi)忙(lan)没留意到
增加setaudiostreamtype的目的是为了实现什么？？

如果是为了实现闹铃效果，我在BASS库的论坛里只找到一小段相对应的问答：[http://www.un4seen.com/forum/?topic=13225.msg104498#msg104498](http://www.un4seen.com/forum/?topic=13225.msg104498#msg104498)

BASS库的作者说到：

> That wasn't possible previously, but I have put up an update (in the 1st post) that adds a "Default (alarm)" device (use device=2 in the BASS_Init call), which outputs on the ALARM stream. To use both MUSIC and ALARM streams, you would call BASS_Init with device=1 (or -1) and again with device=2, and then use BASS_SetDevice to switch the device context as needed.

**Comment by xiezhanyan** [comment]
@ViTess 暂时没有用到setaudiostreamtype，只是想知道有没有类似功能供后续开发使用，另外非常感谢开源此代码，对我们项目帮助很大，thanks
